version: '3.8'

x-postgres-tinode-env-vars: &postgres-tinode-env-vars
  "STORE_USE_ADAPTER": "postgres"

services:
  db:
    image: postgres:15.2
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  tinode-0:
    environment:
      << : *postgres-tinode-env-vars
      "WAIT_FOR": "postgres:5432"
