// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorkflow = "chatbot_workflow"

// Workflow mapped from table <chatbot_workflow>
type Workflow struct {
	ID        int32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string        `gorm:"column:uid;not null" json:"uid"`
	Topic     string        `gorm:"column:topic;not null" json:"topic"`
	Flag      string        `gorm:"column:flag;not null" json:"flag"`
	RuleID    string        `gorm:"column:rule_id;not null" json:"rule_id"`
	Version   int32         `gorm:"column:version;not null" json:"version"`
	Step      int32         `gorm:"column:step;not null" json:"step"`
	Values    JSON          `gorm:"column:values" json:"values"`
	State     WorkflowState `gorm:"column:state;not null" json:"state"`
	CreatedAt time.Time     `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time     `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Workflow's table name
func (*Workflow) TableName() string {
	return TableNameWorkflow
}
