name: App

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server repo
        uses: actions/checkout@v3
        with:
          path: tinode

      - name: Checkout web repo
        uses: actions/checkout@v3
        with:
          repository: sysatom/tinode-webapp
          path: tinode-webapp

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build go
        run: |
          cd tinode && go build -tags mysql -o app github.com/tinode/chat/server
          go build -tags mysql -o help_agent github.com/tinode/chat/server/extra/bots/help/agent
          go build -tags mysql -o server_agent github.com/tinode/chat/server/extra/bots/server/agent

      - name: Build js
        run: cd tinode-webapp && npm install && npm run build

      - name: Copy files
        run: |
          mkdir app/
          mkdir tinode-webapp/static/
          cp -R tinode-webapp/audio/ tinode-webapp/static/
          cp -R tinode-webapp/css/ tinode-webapp/static/
          cp -R tinode-webapp/img/ tinode-webapp/static/
          cp -R tinode-webapp/umd/ tinode-webapp/static/
          cp tinode-webapp/firebase-init.js tinode-webapp/static/
          cp tinode-webapp/index.html tinode-webapp/static/
          cp tinode-webapp/index-dev.html tinode-webapp/static/
          cp tinode-webapp/manifest.json tinode-webapp/static/
          cp tinode-webapp/service-worker.js tinode-webapp/static/
          cp tinode-webapp/version.js tinode-webapp/static/
          cp tinode/app app/
          cp tinode/*_agent app/
          cp -R tinode/server/templ/ app/
          cp -R tinode-webapp/static/ app/
          mv app/app app/server

      - uses: actions/upload-artifact@v3
        with:
          name: tinode
          path: app
