name: Build

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Build
        run: |
          go env
          go build -tags mysql -o tmp github.com/tinode/chat/server
